#!/usr/bin/env ruby

require 'mongo'
require 'active_support/all'

conn = Mongo::Connection.new
db = conn.db('chrono_metrics_development')
coll = db.collection('cc_debits')
coll.create_index('at')
coll.remove

# Create one year's worth of fake CC transaction data
docs = []
start = 1.year.ago.utc.to_i
start = start - (start % 3600)
now = Time.now.utc.to_i
current = start
while current < now
  current += 3600
  value = 20_000 + ((current % 86400)/2) + rand(5_000)
  doc = { :k => 'cc_debits', :v => value, :at => Time.at(current).utc }
  docs << doc
end
puts "Inserting #{docs.size} docs"
coll.insert(docs)
